import { useEffect, useRef, useState } from 'react';
import { Table, Tag, Space, Button, Dropdown, Empty, message, Input, Select } from 'antd';
import {
  MoreOutlined,
  EditOutlined,
  DeleteOutlined,
  SearchOutlined,
  FileTextOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import useAuth from '../../contexts/AuthContext';
import { useHeader } from '../../contexts/HeaderContext';
import { Heading } from '../../components/Heading';
import { GradientButton } from '../../components/ui';
import ComplianceReportFormDrawer from '../../components/quality/ComplianceReportFormDrawer';
import { qualityService } from '../../services/qualityService';
import './ComplianceReportsListPage.scss';

interface ComplianceReport {
  id: string;
  reportId: string;
  reportType: string;
  reportTitle: string;
  status: string;
  generatedBy: string;
  generatedAt: string;
  createdAt: string;
}

export default function ComplianceReportsListPage() {
  const { currentCompany } = useAuth();
  const { setHeaderActions } = useHeader();
  const [reports, setReports] = useState<ComplianceReport[]>([]);
  const [loading, setLoading] = useState(false);
  const [drawerVisible, setDrawerVisible] = useState(false);
  const [selectedReport, setSelectedReport] = useState<ComplianceReport | null>(null);
  const [searchText, setSearchText] = useState('');
  const [selectedType, setSelectedType] = useState<string | undefined>(undefined);
  const [selectedStatus, setSelectedStatus] = useState<string | undefined>(undefined);
  const fetchInProgressRef = useRef(false);

  useEffect(() => {
    setHeaderActions(
      <GradientButton onClick={handleCreateReport} size='small'>
        Create Report
      </GradientButton>
    );

    return () => setHeaderActions(null);
  }, [setHeaderActions]);

  useEffect(() => {
    if (currentCompany) {
      fetchReports();
    }
  }, [currentCompany, searchText, selectedType, selectedStatus]);

  const fetchReports = async () => {
    if (fetchInProgressRef.current) return;

    try {
      fetchInProgressRef.current = true;
      setLoading(true);
      const params: any = {};
      if (searchText) params.search = searchText;
      if (selectedType) params.reportType = selectedType;
      if (selectedStatus) params.status = selectedStatus;

      const data = await qualityService.getComplianceReports(params);
      setReports(data);
    } catch (error: any) {
      console.error('Error fetching reports:', error);
      message.error(error.message || 'Failed to fetch compliance reports');
    } finally {
      setLoading(false);
      fetchInProgressRef.current = false;
    }
  };

  const handleCreateReport = () => {
    setSelectedReport(null);
    setDrawerVisible(true);
  };

  const handleEditReport = (report: ComplianceReport) => {
    setSelectedReport(report);
    setDrawerVisible(true);
  };

  const handleDeleteReport = async (report: ComplianceReport) => {
    try {
      await qualityService.deleteComplianceReport(report.id);
      message.success('Compliance report deleted successfully');
      fetchReports();
    } catch (error: any) {
      message.error(error.message || 'Failed to delete compliance report');
    }
  };

  const handleDrawerClose = () => {
    setDrawerVisible(false);
    setSelectedReport(null);
  };

  const handleDrawerSuccess = () => {
    fetchReports();
    handleDrawerClose();
  };

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      DRAFT: 'default',
      SUBMITTED: 'blue',
      APPROVED: 'green',
      REJECTED: 'red',
    };
    return colors[status] || 'default';
  };

  const columns: ColumnsType<ComplianceReport> = [
    {
      title: 'Report ID',
      dataIndex: 'reportId',
      key: 'reportId',
      width: 120,
      render: (reportId: string) => <span className='report-id'>{reportId}</span>,
    },
    {
      title: 'Report Title',
      dataIndex: 'reportTitle',
      key: 'reportTitle',
      render: (title: string, record: ComplianceReport) => (
        <div style={{ overflow: 'hidden' }}>
          <div
            className='report-title'
            style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}
          >
            {title}
          </div>
          <div
            className='report-type'
            style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}
          >
            {record.reportType}
          </div>
        </div>
      ),
    },
    {
      title: 'Generated By',
      dataIndex: 'generatedBy',
      key: 'generatedBy',
      width: 150,
    },
    {
      title: 'Generated Date',
      dataIndex: 'generatedAt',
      key: 'generatedAt',
      width: 140,
      render: (date: string) => dayjs(date).format('MMM DD, YYYY'),
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      width: 120,
      render: (status: string) => <Tag color={getStatusColor(status)}>{status}</Tag>,
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 100,
      render: (_: any, record: ComplianceReport) => {
        const menuItems = [
          {
            key: 'view',
            icon: <FileTextOutlined />,
            label: 'View Report',
            onClick: () => message.info('View report functionality coming soon'),
          },
          {
            key: 'edit',
            icon: <EditOutlined />,
            label: 'Edit',
            onClick: () => handleEditReport(record),
          },
          {
            type: 'divider' as const,
          },
          {
            key: 'delete',
            icon: <DeleteOutlined />,
            label: 'Delete',
            danger: true,
            onClick: () => handleDeleteReport(record),
          },
        ];

        return (
          <Space>
            <Dropdown menu={{ items: menuItems }} trigger={['click']} placement='bottomRight'>
              <Button type='text' icon={<MoreOutlined />} />
            </Dropdown>
          </Space>
        );
      },
    },
  ];

  return (
    <div className='page-container'>
      <div className='page-header-section'>
        <Heading level={2} className='page-title'>
          Compliance Reports
        </Heading>
      </div>

      <div className='filters-section'>
        <Space size='middle'>
          <Input
            placeholder='Search reports...'
            prefix={<SearchOutlined />}
            value={searchText}
            onChange={e => setSearchText(e.target.value)}
            style={{ width: 250 }}
            allowClear
          />
          <Select
            placeholder='All Types'
            value={selectedType}
            onChange={setSelectedType}
            style={{ width: 180 }}
            allowClear
          >
            <Select.Option value='QUALITY_AUDIT'>Quality Audit</Select.Option>
            <Select.Option value='SAFETY_INSPECTION'>Safety Inspection</Select.Option>
            <Select.Option value='ENVIRONMENTAL'>Environmental</Select.Option>
            <Select.Option value='REGULATORY'>Regulatory</Select.Option>
          </Select>
          <Select
            placeholder='All Status'
            value={selectedStatus}
            onChange={setSelectedStatus}
            style={{ width: 150 }}
            allowClear
          >
            <Select.Option value='DRAFT'>Draft</Select.Option>
            <Select.Option value='SUBMITTED'>Submitted</Select.Option>
            <Select.Option value='APPROVED'>Approved</Select.Option>
            <Select.Option value='REJECTED'>Rejected</Select.Option>
          </Select>
        </Space>
      </div>

      <Table
        columns={columns}
        dataSource={reports}
        loading={loading}
        rowKey='id'
        className='reports-table'
        locale={{
          emptyText: (
            <Empty description='No compliance reports found' image={Empty.PRESENTED_IMAGE_SIMPLE} />
          ),
        }}
        pagination={{
          pageSize: 10,
          showSizeChanger: true,
          showTotal: total => `Total ${total} reports`,
        }}
      />

      <ComplianceReportFormDrawer
        visible={drawerVisible}
        report={selectedReport}
        onClose={handleDrawerClose}
        onSuccess={handleDrawerSuccess}
      />
    </div>
  );
}
